dist: xenial
os: linux
language: php

php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --no-suggest

script:
  - composer test
  - composer build-artifacts

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
